workflows:
  capacitor-ios-workflow:
    name: RentCredit iOS
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        BUNDLE_ID: "com.rentcredit.app"
      node: 18
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Setup Capacitor
        script: |
          npx cap add ios
          npx cap copy ios
      - name: Build iOS (unsigned)
        script: |
          xcodebuild -workspace ios/App/App.xcworkspace -scheme App -configuration Debug -destination generic/platform=iOS CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ios/App/build/Debug-iphoneos/*.app
