workflows:
  ionic-capacitor-ios-workflow:
    name: RentCredit iOS
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        BUNDLE_ID: "com.rentcredit.app"
      node: 18
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web app
        script: npm run build
      - name: Add iOS platform
        script: npx cap add ios
      - name: Copy web assets to iOS
        script: npx cap copy ios
      - name: Install CocoaPods dependencies
        script: cd ios/App && pod install
      - name: Build iOS app (unsigned)
        script: |
          cd ios/App && xcodebuild -workspace App.xcworkspace -scheme App -configuration Debug -destination generic/platform=iOS CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ios/App/build/Debug-iphoneos/*.app
