name: Build Android AAB for Play Store

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'App version (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Create Android WebView Project
      run: |
        # Create project structure
        mkdir -p RentCredit
        cd RentCredit
        
        # Create complete project structure
        mkdir -p app/src/main/java/com/rentcredit/app
        mkdir -p app/src/main/res/values
        mkdir -p app/src/main/res/drawable
        mkdir -p app/src/main/res/mipmap-hdpi
        mkdir -p app/src/main/res/mipmap-mdpi
        mkdir -p app/src/main/res/mipmap-xhdpi
        mkdir -p app/src/main/res/mipmap-xxhdpi
        mkdir -p app/src/main/res/mipmap-xxxhdpi
        
        # Create root build.gradle
        cat > build.gradle << 'EOF'
        buildscript {
            repositories {
                google()
                mavenCentral()
            }
            dependencies {
                classpath 'com.android.tools.build:gradle:8.1.1'
            }
        }
        
        allprojects {
            repositories {
                google()
                mavenCentral()
            }
        }
        
        task clean(type: Delete) {
            delete rootProject.buildDir
        }
        EOF
        
        # Create settings.gradle
        cat > settings.gradle << 'EOF'
        rootProject.name = "RentCredit"
        include ':app'
        EOF
        
        # Create gradle.properties
        cat > gradle.properties << 'EOF'
        org.gradle.jvmargs=-Xmx1536m
        android.useAndroidX=true
        android.enableJetifier=true
        EOF
        
        # Create local.properties
        cat > local.properties << 'EOF'
        sdk.dir=/usr/local/lib/android/sdk
        EOF
        
        # Create app/build.gradle
        cat > app/build.gradle << 'EOF'
        apply plugin: 'com.android.application'
        
        android {
            namespace 'com.rentcredit.app'
            compileSdk 34
            
            defaultConfig {
                applicationId "com.rentcredit.app"
                minSdk 21
                targetSdk 34
                versionCode 1
                versionName "${{ github.event.inputs.release_version }}"
            }
            
            signingConfigs {
                release {
                    storeFile file("../keystore.jks")
                    storePassword "rentcredit2025"
                    keyAlias "rentcredit"
                    keyPassword "rentcredit2025"
                }
            }
            
            buildTypes {
                release {
                    minifyEnabled false
                    signingConfig signingConfigs.release
                    proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
                }
            }
            
            compileOptions {
                sourceCompatibility JavaVersion.VERSION_1_8
                targetCompatibility JavaVersion.VERSION_1_8
            }
        }
        
        dependencies {
            implementation 'androidx.appcompat:appcompat:1.6.1'
            implementation 'com.google.android.material:material:1.10.0'
            implementation 'androidx.webkit:webkit:1.8.0'
        }
        EOF
        
        # Create MainActivity.java
        cat > app/src/main/java/com/rentcredit/app/MainActivity.java << 'EOF'
        package com.rentcredit.app;
        
        import android.os.Bundle;
        import android.webkit.WebSettings;
        import android.webkit.WebView;
        import android.webkit.WebViewClient;
        import androidx.appcompat.app.AppCompatActivity;
        
        public class MainActivity extends AppCompatActivity {
            private WebView webView;
            
            @Override
            protected void onCreate(Bundle savedInstanceState) {
                super.onCreate(savedInstanceState);
                
                webView = new WebView(this);
                setContentView(webView);
                
                WebSettings webSettings = webView.getSettings();
                webSettings.setJavaScriptEnabled(true);
                webSettings.setDomStorageEnabled(true);
                webSettings.setLoadWithOverviewMode(true);
                webSettings.setUseWideViewPort(true);
                webSettings.setSupportZoom(true);
                webSettings.setBuiltInZoomControls(true);
                webSettings.setDisplayZoomControls(false);
                
                webView.setWebViewClient(new WebViewClient());
                webView.loadUrl("https://rentcredit.us");
            }
            
            @Override
            public void onBackPressed() {
                if (webView.canGoBack()) {
                    webView.goBack();
                } else {
                    super.onBackPressed();
                }
            }
        }
        EOF
        
        # Create AndroidManifest.xml
        cat > app/src/main/AndroidManifest.xml << 'EOF'
        <?xml version="1.0" encoding="utf-8"?>
        <manifest xmlns:android="http://schemas.android.com/apk/res/android">
            
            <uses-permission android:name="android.permission.INTERNET" />
            <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
            
            <application
                android:allowBackup="true"
                android:icon="@mipmap/ic_launcher"
                android:label="RentCredit"
                android:theme="@style/Theme.AppCompat.Light.NoActionBar"
                android:usesCleartextTraffic="true">
                <activity
                    android:name=".MainActivity"
                    android:exported="true"
                    android:configChanges="orientation|keyboardHidden|screenSize">
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN" />
                        <category android:name="android.intent.category.LAUNCHER" />
                    </intent-filter>
                </activity>
            </application>
        </manifest>
        EOF
        
        # Create simple purple icon with RC text
        cat > app/src/main/res/values/colors.xml << 'EOF'
        <?xml version="1.0" encoding="utf-8"?>
        <resources>
            <color name="purple">#8B5CF6</color>
        </resources>
        EOF
        
        # Create proguard rules
        touch app/proguard-rules.pro
        
        # Generate keystore
        keytool -genkeypair -v \
          -keystore keystore.jks \
          -alias rentcredit \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -storepass rentcredit2025 \
          -keypass rentcredit2025 \
          -dname "CN=RentCredit, OU=Mobile, O=RentCredit, L=San Francisco, ST=CA, C=US"
    
    - name: Setup Gradle
      run: |
        cd RentCredit
        
        # Download and setup gradle wrapper
        wget https://services.gradle.org/distributions/gradle-8.1.1-all.zip
        unzip gradle-8.1.1-all.zip
        
        # Create wrapper
        gradle-8.1.1/bin/gradle wrapper
        
    - name: Build AAB
      run: |
        cd RentCredit
        
        # Make gradlew executable
        chmod +x gradlew
        
        # Build the AAB
        ./gradlew clean
        ./gradlew bundleRelease
        
        # List output files
        echo "Build outputs:"
        find app/build/outputs -type f -name "*.aab" -o -name "*.apk"
        
    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: RentCredit-${{ github.event.inputs.release_version }}-Android
        path: RentCredit/app/build/outputs/bundle/release/app-release.aab
        
    - name: Generate Upload Instructions
      run: |
        cat > GOOGLE_PLAY_UPLOAD.md << 'EOF'
        # Google Play Store Upload Instructions
        
        ## App Details
        - Package Name: com.rentcredit.app
        - Version: ${{ github.event.inputs.release_version }}
        - File: app-release.aab
        
        ## Upload Steps
        1. Download the AAB file from GitHub Actions artifacts
        2. Go to [Google Play Console](https://play.google.com/console)
        3. Select your app or create new app
        4. Navigate to Release > Production
        5. Click "Create new release"
        6. Upload the AAB file
        7. Complete store listing with:
           - App name: RentCredit
           - Short description: Build credit with rent payments
           - Full description: Track rent, build credit, connect with landlords
           - Category: Finance
           - Content rating: Everyone
        8. Submit for review
        
        ## First Time Setup
        - App name: RentCredit
        - Package name: com.rentcredit.app
        - Default language: English (United States)
        EOF
        
    - name: Upload Instructions
      uses: actions/upload-artifact@v4
      with:
        name: Upload-Instructions
        path: GOOGLE_PLAY_UPLOAD.md
