name: Build RentCredit Mobile App

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build web app for mobile
      run: npm run build
      
    - name: Create mobile web directory
      run: |
        mkdir -p mobile-dist
        cp -r dist/* mobile-dist/
        
    - name: Setup Capacitor
      run: |
        npx cap init "RentCredit" "com.rentcredit.app" --web-dir=mobile-dist
        
    - name: Add iOS platform
      run: npx cap add ios
      
    - name: Sync web assets to iOS
      run: npx cap sync ios
      
    - name: Install CocoaPods dependencies
      run: |
        cd ios/App
        pod install
        
    - name: Build iOS App (Debug)
      run: |
        cd ios/App
        xcodebuild -workspace App.xcworkspace \
                   -scheme App \
                   -configuration Debug \
                   -destination generic/platform=iOS \
                   CODE_SIGNING_ALLOWED=NO \
                   -archivePath App.xcarchive \
                   archive
        
    - name: Export iOS App for distribution
      run: |
        cd ios/App
        mkdir -p build/Debug-iphoneos
        cp -r App.xcarchive/Products/Applications/ build/Debug-iphoneos/
        
    - name: Upload iOS Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rentcredit-ios-app
        path: ios/App/build/Debug-iphoneos/
        retention-days: 30
        
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build web app for mobile
      run: npm run build
      
    - name: Create mobile web directory
      run: |
        mkdir -p mobile-dist
        cp -r dist/* mobile-dist/
        
    - name: Setup Capacitor
      run: |
        npx cap init "RentCredit" "com.rentcredit.app" --web-dir=mobile-dist
        
    - name: Add Android platform
      run: npx cap add android
      
    - name: Sync web assets to Android
      run: npx cap sync android
      
    - name: Make gradlew executable
      run: chmod +x android/gradlew
      
    - name: Build Android APK
      run: |
        cd android
        ./gradlew assembleDebug
        
    - name: Build Android Bundle (AAB)
      run: |
        cd android
        ./gradlew bundleRelease
        
    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: rentcredit-android-apk
        path: android/app/build/outputs/apk/debug/*.apk
        retention-days: 30
        
    - name: Upload Android Bundle
      uses: actions/upload-artifact@v4
      with:
        name: rentcredit-android-bundle
        path: android/app/build/outputs/bundle/release/*.aab
        retention-days: 30
