name: Build RentCredit Mobile App

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build web app for mobile
      run: npm run build
        
    - name: Setup Capacitor project
      run: |
        npx cap init "RentCredit" "com.rentcredit.app" --web-dir=dist
        
    - name: Add iOS platform
      run: npx cap add ios
      
    - name: Sync and update iOS
      run: npx cap sync ios
      
    - name: Setup iOS build environment
      run: |
        cd ios/App
        pod install
        
    - name: Build iOS App
      run: |
        cd ios/App
        xcodebuild -workspace App.xcworkspace \
                   -scheme App \
                   -configuration Debug \
                   -destination generic/platform=iOS \
                   -archivePath RentCredit.xcarchive \
                   archive \
                   CODE_SIGNING_ALLOWED=NO
        
    - name: Extract iOS App
      run: |
        cd ios/App
        mkdir -p build/Debug-iphoneos
        cp -r RentCredit.xcarchive/Products/Applications/ build/Debug-iphoneos/ 2>/dev/null || true
        
    - name: Upload iOS Build
      uses: actions/upload-artifact@v4
      with:
        name: rentcredit-ios-app
        path: ios/App/build/Debug-iphoneos/
        retention-days: 30
        
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build web app for mobile
      run: npm run build
        
    - name: Setup Capacitor project
      run: |
        npx cap init "RentCredit" "com.rentcredit.app" --web-dir=dist
        
    - name: Add Android platform
      run: npx cap add android
      
    - name: Sync and update Android
      run: npx cap sync android
      
    - name: Grant execute permissions
      run: chmod +x android/gradlew
      
    - name: Build Android APK
      run: |
        cd android
        ./gradlew assembleDebug --no-daemon
        
    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: rentcredit-android-apk
        path: android/app/build/outputs/apk/debug/*.apk
        retention-days: 30
